{
 "title": "Materialize Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Cluster Replicas",
   "type": "table",
   "description": "This is a list of replicas with their sizes for the user clusters in this environment.  ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sql_cluster_replicas", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Replica Uptime",
   "type": "timeseries",
   "description": "This is the time since the last restart for each of the replicas on the user clusters. Returns to zero with each restart of each replica, whether planned or because of a crash or OOM condition.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sql_replica_uptime{col=\"uptime_seconds\"}",
     "legendFormat": "{{cluster_name}}.{{replica_name}}"
    }
   ]
  },
  {
   "title": "Cluster Utilization Peak",
   "type": "gauge",
   "description": "peak utilization on available data",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time (\n    (\n        (\n            sum by (cluster_id, cluster_name, replica_id, replica_name) ( sql_cluster_replica_usage{col=\"used_disk_bytes\", cluster_id=~\"u.+\"} )\n            +\n            sum by (cluster_id, cluster_name, replica_id, replica_name) ( sql_cluster_replica_usage{col=\"used_memory_bytes\",cluster_id=~\"u.+\"} )\n        )   \n        /\n            sum by (cluster_id, cluster_name, replica_id, replica_name) ( sql_cluster_replica_usage{col=\"total_memory_bytes\",cluster_id=~\"u.+\"} )\n    )[15d:]\n) * 100",
     "legendFormat": "{{cluster_name}}.{{replica_name}}"
    }
   ]
  },
  {
   "title": "Cluster Utilization By Minute",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "\n    (\n        (\n            sum by (cluster_id, cluster_name, replica_id, replica_name) ( sql_cluster_replica_usage{col=\"used_disk_bytes\", cluster_id=~\"u.+\"} )\n            +\n            sum by (cluster_id, cluster_name, replica_id, replica_name) ( sql_cluster_replica_usage{col=\"used_memory_bytes\",cluster_id=~\"u.+\"} )\n        )   \n        /\n            sum by (cluster_id, cluster_name, replica_id, replica_name) ( sql_cluster_replica_usage{col=\"total_memory_bytes\",cluster_id=~\"u.+\"} )\n    ) * 100",
     "legendFormat": "{{cluster_name}}.{{replica_name}}"
    }
   ]
  },
  {
   "title": "Replica Memory",
   "type": "timeseries",
   "description": "The percentage of available memory that is in use for each user replica. When CC clusters get above ~90%, they will start spilling to disk and stay there until the disk is exhausted before out-of-memory restarts.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sql_cluster_replica_usage{col=\"memory_percent\", replica_id=~\"^u.*\"}",
     "legendFormat": "{{cluster_name}}.{{replica_name}}"
    }
   ]
  },
  {
   "title": "Replica CPU",
   "type": "timeseries",
   "description": "The percentage of available CPU being used by the user replicas. Materialize will often used underutilized CPU cycles for maintenance opportunistically, so a 100% CPU doesn't always indicate CPU starvation for compute tasks, although it can. ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sql_cluster_replica_usage{col=\"cpu_percent\", replica_id=~\"^u.*\"}",
     "legendFormat": "{{cluster_name}}.{{replica_name}}"
    }
   ]
  },
  {
   "title": "Replica Disk",
   "type": "timeseries",
   "description": "Disk is used by CC compute clusters for spilling memory to disk for optimization. Disk is also used by upsert source replicas for deduplication tracking.  When both memory and disk reach 100%, a replica will restart, and can get caught in an \"OOM Loop\"",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sql_cluster_replica_usage{col=\"disk_percent\", replica_id=~\"^u.*\"}",
     "legendFormat": "{{cluster_name}}.{{replica_name}}"
    }
   ]
  },
  {
   "title": "Source Health - Rate of Updates Committed By Source",
   "type": "timeseries",
   "description": "Average updates committed ( written to storage layer ) by the source per second. ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "rate(sql_source_statistics{col=\"updates_committed\"}[$__rate_interval])",
     "legendFormat": "{{source_name}}"
    }
   ]
  },
  {
   "title": "Source Health - Offset Lag",
   "type": "timeseries",
   "description": "Gap between the known upstream offset and the committed offset. Indicates if commits are keeping up with the source. ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sql_source_statistics{col=\"offset_known\"} - on(source_id, source_name) sql_source_statistics{col=\"offset_committed\"}\n",
     "legendFormat": "{{source_name}}"
    }
   ]
  },
  {
   "title": "Source Health - Rehydration Time",
   "type": "timeseries",
   "description": "time ( seconds ) that the last rehydration took, per source",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "sql_source_statistics{col=\"rehydration_latency_seconds\"}",
     "legendFormat": "{{source_name}}"
    }
   ]
  },
  {
   "title": "Sink Health - Uncommitted Messages",
   "type": "timeseries",
   "description": "For sinks, shows the difference between messages staged and committed. Could indicate a stuck sink if these messages start backing up.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "sql_sink_statistics{col=\"messages_staged\"} - on(sink_id, sink_name) sql_sink_statistics{col=\"messages_committed\"}",
     "legendFormat": "{{sink_name}}"
    }
   ]
  },
  {
   "title": "Object Freshness ( Lag )",
   "type": "timeseries",
   "description": "For each object, how many seconds behind the current time was the last update",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "sql_object_freshness{col=\"lag_ms\"} / 1000",
     "legendFormat": "{{object_name}}"
    }
   ]
  },
  {
   "title": "Max Query Latency Per Cluster",
   "type": "timeseries",
   "description": "For each user cluster, what was the maximum latency observed for an ad-hoc query in the last 3 days. This comes from the query time collected in the mz_internal.mz_recent_activity_log_redacted table. ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "sql_query_latency{col=\"max_latency\"}",
     "legendFormat": "{{cluster_name}}.{{replica_name}}"
    }
   ]
  }
 ]
}